[package]
name = "anyeyeballs"
version = "0.1.0"
authors = ["Max Franke <mfranke@inet.tu-berlin.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pnet = "0.27.2"
socket2 = "0.3.19"
bit-vec = "0.6.3"